### PR TITLE
TITLE: UofT-DSI | SQL - Homework 3, 4, 5, 6

### PR DESCRIPTION
**Pull request by KathrynVozoris**
Update homework_3.sql
TITLE: UofT-DSI | SQL- Homework 3

## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports) 
Adding SQL code to answer the given questions.

## What did you learn from the changes you have made?

I learned how to use the aggregate functions COUNT(), JOIN() and the HAVING() clause. I also learned how deal with dates, and use  the strftime() function, and apply groupings. Additionally, it was good practice in thinking through the logic of the queries, and nesting of functions. It also helped reinforce the importance of the order of the commands.

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
No.

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?

I had to look over the notes from class, and examples. I was able to follow these and needed to check the syntax carefully.  

## How were these changes tested?

I checked my work by doing some tests, and double-checking results with the values in the original database.

## Checklist
- [ X] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by KathrynVozoris** [comment]
Update homework_2.sql
 UofT-DSI | SQL - Homework 2

## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)

I have included answers to homework 2 in SQL code.

## What did you learn from the changes you have made?

I learned about the syntax of SQL, and the order the commands need to be in for the code to run. I learned how to create a new column, use a CASE statement,  filter columns by defining criteria and how to use INNER JOIN to join two tables through the common elements of a given column. I also learned that one has to look at everything carefully.

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?

I tried using IN to search for 'pepper' in the product_name column. This didn't work! Instead we need product_name LIKE '%pepper%'.

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?

I had to look through the notes from class carefully to correct my syntax, and understand how the commands in SQL run.

## How were these changes tested?

I tested the changes in DB browser, and tried to look at the tables carefully.

## A reference to a related issue in your repository (if applicable)

## Checklist
- [ X] I can confirm that my changes are working as intended

**Comment by SidraBushra** [comment]
HW1 marked.

**Comment by KathrynVozoris** [comment]
Update homework_4.sql

TITLE: UofT-DSI | SQL – Homework 4

## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)

I answered the coding questions in the homework_4.sql file in my sql homeworks branch.

## What did you learn from the changes you have made?

I learned the difference between IFNULL and COALESCE. I learned how to use the COUNT function combined with GROUP BY.  I learned how use the substr and instr functions. I also learned how to use REGEX to check for digits in a string, and apply the UNION clause. I also learned that it takes a lot of practice to remember the syntax and order of operations.

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?

I initially had trouble with the count() function -- I was thinking of it in terms of a “for loop”, that is to loop through each customer_id and each product_id and count the number of times a given customer bought a specified product. I realized this can be done using the GROUP BY clause . This helped clarify for me how GROUP BY works.

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
I had trouble with the question involving COUNT(). I had to look over examples, and think about what WHERE, HAVING, ORDER BY and GROUP BY can do. After some reflection, I was able to see how GROUP BY could be used here to get the filtering needed. 
The exercises were great practice, and I felt more confident after each completion. The first few were challenging!

## How were these changes tested?
I double checked the results by comparing them to the original data sets, and visually worked out what the result should be. In some cases, I was able to do another query to help me to do theses checks more readily.

## A reference to a related issue in your repository (if applicable)

## Checklist
- [ X] I can confirm that my changes are working as intended

**Comment by SidraBushra** [comment]
HW2 marked.

**Comment by KathrynVozoris** [comment]
TITLE: UofT-DSI | SQL - Homework 5

## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
Answering the questions in homework 5.

## What did you learn from the changes you have made?

I learned how to use the CROSS JOIN and UPDATE functions. I learned how add a RANK() to a table, and filter the result according to rank number, using a GROUP BY clause. Additionally I learned how to nest multiple subqueries using JOINs.

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
I had originally had some trouble with first question and did it using temporary tables instead of multiple subqueries. Working through it carefully, and thinking about how to use the groupings with the LEFT JOIN function, I was able to create the query using a CROSS JOIN as suggested.

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
I had a difficult time with the syntax, and using the more complex combination of functions and subqueries. I had to look over the results step by step, and check the tables carefully to see which column I was referencing. I also had to look up the syntax of the functions, to make sure I had the order correct in my lay out of the queries.

## How were these changes tested?

I looked at the results and compared them to what I was trying to achieve from the original given tables.

## A reference to a related issue in your repository (if applicable)

## Checklist
- [x] I can confirm that my changes are working as intended

**Comment by KathrynVozoris** [comment]
TITLE: UofT-DSI | SQL - Homework 6

## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
Adding my reflections on our discussion on data ethics.

## What did you learn from the changes you have made?

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?

## How were these changes tested?

## A reference to a related issue in your repository (if applicable)

## Checklist
- [ ] I can confirm that my changes are working as intended

**Comment by SidraBushra** [comment]
HW 3 to 6 marked.

**Pull request closed without merging**
